[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "attention-predict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    # Data handling
    "h5py",
    "pyarrow",
    # Utils
    "tqdm",
    "flv-utils",
    "jaxtyping",
    "einops",
]

[dependency-groups]
dev = [
    # Interactive plotting
    "altair",
    "vegafusion",
    "vl-convert-python",
    # Notebook
    "marimo[recommended]",
    # Typing
    "mypy",
    "types-tqdm",
    "watchdog",
    "pytest",
]

[project.optional-dependencies]
cpu = [
  "torch",
]
cuda = [
  "torch",
]
rocm = [
  "torch",
]

[tool.uv]
default-groups = ["dev"]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cuda" },
    { extra = "rocm"},
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu124", extra = "cuda" },
  { index = "pytorch-rocm63", extra = "rocm" },
]
flv-utils = { git = "ssh://git@github.com/flavell-lab/flv_utils" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"

[[tool.uv.index]]
name = "pytorch-rocm63"
url = "https://download.pytorch.org/whl/rocm6.3"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
exclude = [
  "notebooks",
  "scripts",
  "old_tests",
  "__pycache__",
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]